### PR TITLE
computed proportionality metrics

### PR DESCRIPTION
**Pull request by adienes**
might be better suited for a notebook? but if you just run this file you should get a sense of what's going on

### CODE REVIEW

**Comment by fsargent** [comment]
Need to add pulp to pipenv. 
would you write an example usage of this?

**Review by fsargent — CHANGES_REQUESTED** [review]
Would you update the pipenv and put in an example?

**Comment by adienes** [comment]
@fsargent did that addition work for pipenv?

I tried to include an example usage down after `if __name__=="__main__":` , or were you thinking in a separate file?

**Review by fsargent — APPROVED** [review]

**Comment by fsargent** [comment]
That LGTM!

**Pull request merged**
